# reporter/reproducer.py
import os

class AnvilRegressionGenerator:
    """Generates standalone Python regression test suites for detected crashes."""

    def generate_test_case(self, target_cmd: str, payload: str, exit_code: str, output_dir: str = "tests/regression") -> str:
        os.makedirs(output_dir, exist_ok=True)
        filepath = os.path.join(output_dir, "test_crash_repro.py")

        escaped_payload = repr(payload)

        test_code = f"""# Auto-generated by ANVIL Regression Generator
import unittest
import subprocess
import sys

class TestAnvilCrashReproduction(unittest.TestCase):
    def test_reproduce_crash(self):
        \"\"\"Verifies whether the target process gracefully handles the crash payload.\"\"\"
        target_command = "{target_cmd}".split() + [{escaped_payload}]
        
        process = subprocess.Popen(
            target_command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        stdout, stderr = process.communicate()
        
        # A non-crash resolution means the process handled the payload without unhandled exit code {exit_code}
        self.assertNotEqual(
            process.returncode, 
            {exit_code if str(exit_code).isdigit() else 139}, 
            f"Vulnerability persistent! Process crashed with exit code {{process.returncode}}"
        )

if __name__ == '__main__':
    unittest.main()
"""

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(test_code)

        print(f"[ANVIL REPRODUCE] Regression test case generated at: {filepath}")
        return filepath


if __name__ == "__main__":
    gen = AnvilRegressionGenerator()
    gen.generate_test_case("python ./tests/samples/vuln.py", "' OR 1=1 --", "140")