# .github/workflows/anvil-sec.yml
name: ANVIL Gatekeeper Audit

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  security-scan:
    name: AppSec Pipeline
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install ANVIL Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml psutil

    - name: Execute ANVIL Gatekeeper
      run: python main.py "python ./tests/samples/vuln.py" --mode gatekeeper
      continue-on-error: true

    - name: Upload SARIF Report to GitHub Security Center
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: reports/anvil_report.sarif
        category: anvil-appsec
